server:
  port: 8082
  context-path: /
spring:
  datasource:
    name: mysql_provider
    url: jdbc:mysql://192.168.90.112:3306/sy_dev??serverTimezone=GMT%2B8&useSSL=FALSE
    username: mysqlSy
    password: Mysql@2021
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.example.domin
